os: linux
jobs:
  include:
    - name: "Main"
      language: java
    - name: "Documentation"
      language: node_js
      node_js: lts/*
      before_install:
        - cd src/main/docs
      install:
        - npm install
        - npm install -g gulp-cli
      script:
        - gulp build
